"""added new column

Revision ID: 5106c376fcae
Revises: aa7191adbd59
Create Date: 2025-12-26 14:06:56.925368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5106c376fcae'
down_revision: Union[str, Sequence[str], None] = 'aa7191adbd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('orders_product_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    op.add_column('orders_items', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('payments', sa.Column('pay_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('payments', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'pay_amount')
    op.drop_column('orders_items', 'total_price')
    op.add_column('orders', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('orders_product_id_fkey'), 'orders', 'products', ['product_id'], ['id'])
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
