"""added new column

Revision ID: 6396df0f27cf
Revises: 2e0a40cd4f9c
Create Date: 2025-12-26 16:00:49.443290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6396df0f27cf'
down_revision: Union[str, Sequence[str], None] = '2e0a40cd4f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
